import 'package:flutter/material.dart';

// keep ecosystem data separate from UI
class OpportunityRepository {
  // store recognized startup entries
  static final List<Map<String, dynamic>> aluStartups = [
    {'name': 'Zuri', 'init': 'ZH', 'color': const Color(0xFF0C4E33), 'verified': true},
    {'name': 'GreenRoute', 'init': 'GR', 'color': const Color(0xFF1F8A5F), 'verified': true},
    {'name': 'Soma', 'init': 'SS', 'color': const Color(0xFF445566), 'verified': true},
    {'name': 'FarmWave', 'init': 'FW', 'color': const Color(0xFFB7791F), 'verified': true},
    {'name': 'Nuru', 'init': 'NC', 'color': const Color(0xFF2F6F4E), 'verified': true},
    {'name': 'Kuja', 'init': 'KC', 'color': const Color(0xFF9CA3AF), 'verified': false},
  ];

  // store marketplace metrics data
  static final List<Map<String, dynamic>> allOpportunities = [
    {
      'id': 'opp_1',
      'logoInit': 'ZH',
      'logoColor': const Color(0xFF0C4E33),
      'companyName': 'Zuri Health',
      'roleTitle': 'Frontend Engineer Intern',
      'workplaceSetting': 'On-site',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Engineering',
      'category': 'Engineering',
      'stipend': 'RWF 80,000/month',
      'spotsLeft': '2 spots left',
      'daysLeft': '14d left',
    },
    {
      'id': 'opp_2',
      'logoInit': 'ZH',
      'logoColor': const Color(0xFF0C4E33),
      'companyName': 'Zuri Health',
      'roleTitle': 'Product Design Intern',
      'workplaceSetting': 'On-site',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Design',
      'category': 'Design',
      'stipend': 'RWF 70,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '17d left',
    },
    {
      'id': 'opp_3',
      'logoInit': 'GR',
      'logoColor': const Color(0xFF1F8A5F),
      'companyName': 'GreenRoute',
      'roleTitle': 'Operations & Logistics Analyst',
      'workplaceSetting': 'On-site',
      'duration': '6 months',
      'jobType': 'Internship',
      'department': 'Operations',
      'category': 'Operations',
      'stipend': 'RWF 95,000/month',
      'spotsLeft': '3 spots left',
      'daysLeft': '8d left',
    },
    {
      'id': 'opp_4',
      'logoInit': 'FW',
      'logoColor': const Color(0xFFB7791F),
      'companyName': 'FarmWave',
      'roleTitle': 'ML Research Intern',
      'workplaceSetting': 'On-site',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Research',
      'category': 'Research',
      'stipend': 'RWF 90,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '15d left',
    },
    {
      'id': 'opp_5',
      'logoInit': 'NC',
      'logoColor': const Color(0xFF2F6F4E),
      'companyName': 'Nuru Capital',
      'roleTitle': 'Community Engagement Coordinator',
      'workplaceSetting': 'On-site',
      'duration': '3 months',
      'jobType': 'Part-time',
      'department': 'Community',
      'category': 'Community',
      'stipend': 'RWF 45,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '28d left',
    },
    {
      'id': 'opp_6',
      'logoInit': 'SS',
      'logoColor': const Color(0xFF445566),
      'companyName': 'Soma Studio',
      'roleTitle': 'Content Creator & Curriculum Researcher',
      'workplaceSetting': 'Remote',
      'duration': '4 months',
      'jobType': 'Part-time',
      'department': 'Content',
      'category': 'Content',
      'stipend': 'RWF 40,000/month',
      'spotsLeft': '2 spots left',
      'daysLeft': '21d left',
    },
    {
      'id': 'opp_7',
      'logoInit': 'SS',
      'logoColor': const Color(0xFF445566),
      'companyName': 'Soma Studio',
      'roleTitle': 'Backend Node.js Developer',
      'workplaceSetting': 'Remote',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Engineering',
      'category': 'Engineering',
      'stipend': 'RWF 60,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '10d left',
    },
    {
      'id': 'opp_8',
      'logoInit': 'KC',
      'logoColor': const Color(0xFF9CA3AF),
      'companyName': 'Kuja Collective',
      'roleTitle': 'Systems Integration Tester',
      'workplaceSetting': 'On-site',
      'duration': '6 months',
      'jobType': 'Project',
      'department': 'Engineering',
      'category': 'Engineering',
      'stipend': 'RWF 110,000/month',
      'spotsLeft': '3 spots left',
      'daysLeft': '5d left',
    },
  ];

  // store applications submitted
  static final List<Map<String, dynamic>> myApplications = <Map<String, dynamic>>[
    {
      'id': 'opp_x1',
      'logoInit': 'SS',
      'logoColor': const Color(0xFF445566),
      'companyName': 'Soma Studio',
      'roleTitle': 'Flutter Developer Intern',
      'workplaceSetting': 'Remote',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Engineering',
      'stipend': 'RWF 75,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '20d left',
      'isApplied': true,
      'statusLabel': 'Shortlisted',
      'statusStep': 1, // shortlisted
      'appliedDate': 'Applied Jul 8',
      'justificationText': '"I am passionate about EdTech and have built three Flutter apps with Firebase integration. I would love to contribute to..."',
    },
    {
      'id': 'opp_4', 
      'logoInit': 'FW',
      'logoColor': const Color(0xFFB7791F),
      'companyName': 'FarmWave',
      'roleTitle': 'ML Research Intern',
      'workplaceSetting': 'On-site',
      'duration': '3 months',
      'jobType': 'Internship',
      'department': 'Research',
      'stipend': 'RWF 90,000/month',
      'spotsLeft': '1 spot left',
      'daysLeft': '15d left',
      'isApplied': true,
      'statusLabel': 'Under Review',
      'statusStep': 0, // under review
      'appliedDate': 'Applied Jul 9',
      'justificationText': '"My ML coursework and crop disease detection project make me a strong candidate for this role at FarmWave."',
    }
  ];
}
